### ISSUE TITLE
Open Questions regarding BIDS convention of dataset

### ISSUE THREAD

**Issue by jqmcginnis** [sct-pipeline/bavaria-quebec#10]
To ensure we have a 100% BIDS compliant dataset, several question still need to be addressed. This is the current state of the raw BIDS-conform dataset (unstitched):

- [ ] LICENSE description file:

As this dataset is strictly confidential, which LICENSE would we like to refer to? 

- [ ] stitched files by scanner (without using Glcoker et al approach):

In the current dataset, we have sessions where a stitched sagittal mask would be already available, as some scanners (Siemens, Phillips) already provide these. I personally would not include these in the dataset, we will probably never make use of these scanner-stitched images and currently generate/process all sagittal chunks using `sct-image -stitch`  anyway. Do you agree?

- [ ] sidecar json conventions:

Do we have an example of what information we would like to store in the jsons accompanying the lesion masks?

**Comment by jcohenadad** [comment]
> Do we have an example of what information we would like to store in the jsons accompanying the lesion masks?

https://bids-specification.readthedocs.io/en/stable/05-derivatives/03-imaging.html#masks
