### ISSUE TITLE
Invoking standalone python script to merge jsons from sct_run_batch

### ISSUE THREAD

**Issue by jqmcginnis** [sct-pipeline/bavaria-quebec#12]
Until now, we have only looked at the merging of the image files (i.e. T2w axial and sagittal). However, each of these files is accompanied (complying to the BIDS convention) by a sidecar json file, e.g.:

```
├── sub-m017255_ses-20120501_acq-ax_chunk-1_dseg.json
├── sub-m017255_ses-20120501_acq-ax_chunk-1_dseg.nii.gz
├── sub-m017255_ses-20120501_acq-ax_chunk-1_T2w.json
├── sub-m017255_ses-20120501_acq-ax_chunk-1_T2w.nii.gz
├── sub-m017255_ses-20120501_acq-ax_chunk-2_dseg.json
├── sub-m017255_ses-20120501_acq-ax_chunk-2_dseg.nii.gz
├── sub-m017255_ses-20120501_acq-ax_chunk-2_T2w.json
├── sub-m017255_ses-20120501_acq-ax_chunk-2_T2w.nii.gz
├── sub-m017255_ses-20120501_acq-ax_chunk-3_dseg.json
├── sub-m017255_ses-20120501_acq-ax_chunk-3_dseg.nii.gz
├── sub-m017255_ses-20120501_acq-ax_chunk-3_T2w.json
├── sub-m017255_ses-20120501_acq-ax_chunk-3_T2w.nii.gz
├── sub-m017255_ses-20120501_acq-sag_chunk-1_T2w.json
├── sub-m017255_ses-20120501_acq-sag_chunk-1_T2w.nii.gz
├── sub-m017255_ses-20120501_acq-sag_chunk-2_T2w.json
├── sub-m017255_ses-20120501_acq-sag_chunk-2_T2w.nii.gz
```

To merge the jsons in a similar way, I currently plan to have the following strategy:

1) We have a script (which is located in the bavaria quebec repository) that we call from the bash script we pass to `sct_run_batch -script preprocess_spine_db.sh`.

2) This [script](https://github.com/sct-pipeline/bavaria-quebec/blob/jqm/spine_pipeline/source/pipeline/spinal_cord/merge_jsons.py) basically gathers all information from the sidecar jsons, merges the information into a list and either outputs a list of values (if different) or a single value for the key.

Example:

` 'Manufacturer': 'Philips Medical Systems', 'ManufacturerModelName': 'Achieva', 'PatientSex': 'F',..., ''SliceThickness': 4.0, 'RepetitionTime': [3292.79516601562, 4303.81640625, 2341.8681640625], 'EchoTime': 90.0, 'NumberOfAverages': [4.0, 4.0, 3.0], 'ImagingFrequency': [127.775144, 127.775019, 127.774909999999], ...`

2) Similar to the stitching command, we call it from the bash-based command script, i.e. directly in it:

```
# obtain the directory where the script is located
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if (( ${#sag_files[@]} > 1))
then
    sct_image -i ${sag_files[@]} -o "${file}_acq-sag_T2w.nii.gz" -stitch -qc "${PATH_QC}"
    python3 "${SCRIPT_DIR}/merge_jsons.py" -i ${sag_files_json[@]} -o "${file}_acq-sag_T2w.json"
fi
```
Naturally, `merge_json.py` cannot be located in the bash script, as it does not get copied to the derivatives/results folder. 

Question: 
1. What would be the most practical yet elegant way to invoke the python script in the script we pass to `sct_run_batch`?
2. Any feedback w.r.t. to json merging is welcome :slightly_smiling_face: !

Cheers,
Julian

**Comment by sandrinebedard** [comment]
Hi Julian!

I've done this a few times for some projects!

Usually, at the beggining of the script, I initialize a variable with the path of the script.

Here are 2 batch scripts where I do that:
- https://github.com/sct-pipeline/pmj-based-csa/blob/main/process_data.sh
- https://github.com/sct-pipeline/contrast-agnostic-softseg-spinalcord/blob/main/process_data.sh

For example, in my case, the script was directly in the folder of the repo, so the initial working directory (where we run sct_run_batch):

```
# Save script path
PATH_SCRIPT=$PWD

...

 # Add padding to seg to overcome edge effect
 python ${PATH_SCRIPT}/pad_seg.py -i ${fileseg}.nii.gz -o ${fileseg}_pad.nii.gz
```

If your scripts are not in the initial working directory, you could also pass it as an argument in sct_run_batch, with the flag `-script-args`
 and you can retreive it in your script since it will be in `$2`.

Hope this answers your questions!

**Comment by jqmcginnis** [comment]
Thank you very much for the excellent input and examples, I opted for option two (flag `-script-args`) in 56a3348.
