### ISSUE TITLE
document strategy for creating masks

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/bavaria-quebec#7]
Based on meeting discussion, the axial lesion seg masks are created within the BIDSification script. The way is works is:
- eg: if there are 3 chunks (1,2,3) and only one chunk (2) has lesion segmentation, the script will fetch the DICOM data for chunks 1 and 3, and create an image with only zeros, that is called 'ax-lesion_chunk1' and 'ax-lesion_chunk3'.

**Comment by jqmcginnis** [comment]
When taking a look at several examples to verify the range of values in the lesion mask, I noticed that:

1) Rater A has segmented the axial images using {1} for lesion mask and {0} for non-lesion mask.
2) Rater B employs different non-zero values to indicate the lesion (taking a guess, I would assume that the rater used different colors in BrainSeg3D to mark the lesion. For instance, mask value range could be  {0,2.47081804} , {0, 2.157}, {0, 2.0} or {0,1}.

Thus, we binarize the segmentation file chunks.

```
for i in "${ax_lesion_files[@]}"
do
   sct_maths -i $i -bin 1e-12 -o $i
done
```

**Comment by jqmcginnis** [comment]
This has been adressed in 49bd950.
